------------------------------------------------------ PICPDS
DROP TABLE PICPDS
CASCADE CONSTRAINTS;

CREATE TABLE PICPDS(
   SEQ NUMBER(10) NOT NULL PRIMARY KEY,
   ID VARCHAR2(50) NOT NULL,
   CATEGORY VARCHAR2(100) NOT NULL,
   TAGS VARCHAR2(500),
   UPLOADDATE DATE NOT NULL,
   FILENAME VARCHAR2(50) NOT NULL,
   READCOUNT NUMBER(10) NOT NULL,
   DOWNCOUNT NUMBER(10) NOT NULL,
   FSAVENAME VARCHAR2(50)
   CONSTRAINT fk_picpds_id FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);
SELECT * from PICPDS

DROP SEQUENCE PICPDS_SEQ;

CREATE SEQUENCE PICPDS_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE picpds 
ADD (FSAVENAME varchar2(50));

INSERT INTO PICPDS
VALUES (PICPDS_SEQ.NEXTVAL, dh, )
---------------------------------------------------- PDSREPLY
DROP TABLE PDSREPLY
CASCADE CONSTRAINTS;

CREATE TABLE PDSREPLY(
   PDSSEQ NUMBER(10) NOT NULL,
   RESEQ NUMBER(10) NOT NULL PRIMARY KEY,
   ID VARCHAR2(50) NOT NULL,
   CONTENT VARCHAR2(500) NOT NULL,
   REREF NUMBER(10),
   WDATE DATE NOT NULL,
   DEL NUMBER(1) NOT NULL,
   TOWHOM VARCHAR2(50),
   READ NUMBER(1),
   CONSTRAINT fk_TOWHOM FOREIGN KEY(TOWHOM) REFERENCES MEMBER(ID),
   CONSTRAINT fk_pdsreply_seq FOREIGN KEY(PDSSEQ) REFERENCES PICPDS(SEQ),
   CONSTRAINT fk_pdsreply_reref FOREIGN KEY(REREF) REFERENCES PDSREPLY(RESEQ)
);

insert into PDSREPLY
values (1, PDSREPLY_RESEQ.nextval, 'dh2', '퍼가요', null, sysdate, 0);
insert into PDSREPLY
values (1, PDSREPLY_RESEQ.nextval, 'dh', '네', 1, sysdate, 0);
insert into PDSREPLY
values (1, PDSREPLY_RESEQ.nextval, 'dh2', '감사합니다', 1, sysdate, 0);
insert into PDSREPLY
values (1, PDSREPLY_RESEQ.nextval, 'dh2', '감사합니다', NULL, sysdate, 0);
insert into PDSREPLY
values (1, PDSREPLY_RESEQ.nextval, 'dh', '네', NULL, sysdate, 0);

DROP SEQUENCE PDSREPLY_RESEQ;

CREATE SEQUENCE PDSREPLY_RESEQ
START WITH 6
INCREMENT BY 1;

SELECT * FROM PDSREPLY WHERE PDSSEQ = 1 ORDER BY REREF ASC, RESEQ ASC 
SELECT * FROM PDSREPLY  

ALTER TABLE PDSREPLY 
ADD(
	TOWHOM VARCHAR2(50),
	READ NUMBER(1),
 	CONSTRAINT fk_TOWHOM FOREIGN KEY(TOWHOM) REFERENCES MEMBER(ID)
);

---------------------------------------------------- PDSLIKE
DROP TABLE PDSLIKE
CASCADE CONSTRAINTS;

CREATE TABLE PDSLIKE(
   PDSSEQ NUMBER(10) NOT NULL,
   ID VARCHAR2(50) NOT NULL,
   CONSTRAINT fk_pdslike_pdsseq FOREIGN KEY(PDSSEQ) REFERENCES PICPDS(SEQ),
   CONSTRAINT fk_pdslike_id FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);

---------------------------------------------------- FOLLOW
DROP TABLE FOLLOW
CASCADE CONSTRAINTS;

CREATE TABLE FOLLOW(
   FOLLOWERID VARCHAR2(50) NOT NULL,
   FOLLOWEEID VARCHAR2(50) NOT NULL,
   CONSTRAINT fk_follow_followerid FOREIGN KEY(FOLLOWERID) REFERENCES MEMBER(ID),
   CONSTRAINT fk_follow_followeeid FOREIGN KEY(FOLLOWEEID) REFERENCES MEMBER(ID)
);

---------------------------------------------------- PDSALL
DROP VIEW PDSALL;

CREATE VIEW PDSALL (SEQ, ID, CATEGORY, TAGS, UPLOADDATE, FILENAME, READCOUNT, DOWNCOUNT, FSAVENAME, LIKECOUNT, REPLYCOUNT)
AS
SELECT DISTINCT P.SEQ, P.ID, P.CATEGORY, P.TAGS, P.UPLOADDATE, P.FILENAME, P.READCOUNT, P.DOWNCOUNT, P.FSAVENAME,
		(SELECT COUNT(*) FROM PDSLIKE, PICPDS WHERE PICPDS.SEQ = PDSLIKE.PDSSEQ),
		(SELECT COUNT(*) FROM PDSREPLY, PICPDS WHERE PICPDS.SEQ = PDSREPLY.PDSSEQ)
FROM PDSLIKE, PICPDS P, PDSREPLY

select * from pdsall

